"use client";

import { useState } from "react";
import { Button, StatusBadge } from "@/components/ui";
import { apiClient, ApiError } from "@/lib/apiClient";
import { InvoiceStatus, type InvoiceDto } from "@/lib/apiTypes";

function label(invoice: InvoiceDto) { if (invoice.status === InvoiceStatus.Paid) return ["Lunas", "green"] as const; if (invoice.status === InvoiceStatus.ProofUploaded) return ["Menunggu konfirmasi", "amber"] as const; return ["Belum dibayar", "amber"] as const; }

export function TenantBillingTable({ initialInvoices }: { initialInvoices: InvoiceDto[] }) {
  const [invoices, setInvoices] = useState(initialInvoices); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function confirm(id: string) { setBusy(id); setError(null); try { await apiClient.post(`/sa/invoices/${id}/confirm-payment`); setInvoices((items) => items.map((item) => item.id === id ? { ...item, status: InvoiceStatus.Paid } : item)); } catch (err) { setError(err instanceof ApiError ? err.message : "Invoice belum bisa dikonfirmasi."); } finally { setBusy(null); } }
  return <div className="flex flex-col gap-3">{error && <p role="alert" className="border-l-2 border-status-red bg-status-red-bg p-3 text-sm">{error}</p>}<div className="divide-y divide-border border-y border-border lg:hidden">{invoices.map((invoice) => { const [text, tone] = label(invoice); return <div key={invoice.id} className="flex flex-col gap-2 py-4"><div className="flex items-center justify-between gap-3"><span className="font-medium text-ink">{new Date(invoice.periodMonth).toLocaleDateString("id-ID", { month: "long", year: "numeric" })}</span><StatusBadge status={tone} label={text} /></div><span className="text-sm text-ink-muted">Rp {invoice.amount.toLocaleString("id-ID")}</span>{invoice.status === InvoiceStatus.ProofUploaded && <Button size="md" onClick={() => void confirm(invoice.id)} loading={busy === invoice.id}>Konfirmasi pembayaran</Button>}</div>; })}{invoices.length === 0 && <p className="py-6 text-sm text-ink-muted">Belum ada invoice untuk tenant ini.</p>}</div><div className="hidden overflow-x-auto border-y border-border lg:block"><table className="w-full text-left text-sm"><thead className="text-ink-muted"><tr><th className="py-3 pr-4 font-medium">Periode</th><th className="py-3 pr-4 font-medium">Jumlah</th><th className="py-3 pr-4 font-medium">Status</th><th className="py-3 font-medium">Aksi</th></tr></thead><tbody className="divide-y divide-border">{invoices.map((invoice) => { const [text, tone] = label(invoice); return <tr key={invoice.id}><td className="py-3 pr-4 text-ink">{new Date(invoice.periodMonth).toLocaleDateString("id-ID", { month: "long", year: "numeric" })}</td><td className="py-3 pr-4 text-ink">Rp {invoice.amount.toLocaleString("id-ID")}</td><td className="py-3 pr-4"><StatusBadge status={tone} label={text} /></td><td className="py-3">{invoice.status === InvoiceStatus.ProofUploaded && <Button size="md" onClick={() => void confirm(invoice.id)} loading={busy === invoice.id}>Konfirmasi pembayaran</Button>}</td></tr>; })}</tbody></table></div></div>;
}
