<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutDir>C:\Users\maste\AppData\Local\Temp\vokasia\bin\Vokasia.Domain\</OutDir>
    <IntermediateOutputPath>C:\Users\maste\AppData\Local\Temp\vokasia\obj\Vokasia.Domain\</IntermediateOutputPath>
  </PropertyGroup>

</Project>
