<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Vokasia.Worker-2281657a-a7c8-4ade-b00f-afc4e1f4909d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.24" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="QuestPDF" Version="2026.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vokasia.Domain\Vokasia.Domain.csproj" />
    <ProjectReference Include="..\Vokasia.Infrastructure\Vokasia.Infrastructure.csproj" />
  </ItemGroup>
</Project>
