"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { apiClient, ApiError } from "@/lib/apiClient";
import { type CompanyDto, type MajorOptionDto, type PeriodSummary, type PlacementDto, type SchoolUserDto, type StudentDto, type TenantMentorDetailDto, type TenantMentorSummaryDto } from "@/lib/apiTypes";
import { EmptyState, Icon, StatusBadge } from "@/components/ui";
import { PlacementWizard } from "./PlacementWizard";

interface Props {
  periods: PeriodSummary[];
  periodId?: string;
  students: StudentDto[];
  staff: SchoolUserDto[];
  companies: CompanyDto[];
  majors: MajorOptionDto[];
  placements?: PlacementDto[];
  mentors?: TenantMentorSummaryDto[];
}

type View = "placements" | "students" | "companies" | "mentors";

export function OperationsWorkspace({ periods, periodId = "", students: initialStudents, staff, companies: initialCompanies, majors, placements: initialPlacements = [], mentors = [] }: Props) {
  const [view, setView] = useState<View>("placements");
  const [students, setStudents] = useState(initialStudents);
  const [companies, setCompanies] = useState(initialCompanies);
  const [placements, setPlacements] = useState(initialPlacements);
  const [selected, setSelected] = useState<string[]>([]);
  const [query, setQuery] = useState("");
  const [showStudentForm, setShowStudentForm] = useState(false);
  const [showCompanyForm, setShowCompanyForm] = useState(false);
  const [showWizard, setShowWizard] = useState(false);
  const [selectedCompany, setSelectedCompany] = useState<CompanyDto | null>(null);
  const [selectedMentor, setSelectedMentor] = useState<TenantMentorDetailDto | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const studentById = useMemo(() => new Map(students.map((student) => [student.id, student])), [students]);
  const companyById = useMemo(() => new Map(companies.map((company) => [company.id, company])), [companies]);
  const visiblePlacements = placements.filter((placement) => `${studentById.get(placement.studentId)?.fullName ?? ""} ${companyById.get(placement.companyId)?.name ?? ""}`.toLowerCase().includes(query.toLowerCase().trim()));

  async function run(action: () => Promise<void>) {
    setBusy(true); setError(null); setMessage(null);
    try { await action(); } catch (err) { setError(err instanceof ApiError ? err.message : "Perubahan belum tersimpan. Coba lagi."); } finally { setBusy(false); }
  }

  async function openMentor(mentor: TenantMentorSummaryDto) {
    try { setError(null); setSelectedMentor(await apiClient.get<TenantMentorDetailDto>(`/tenant-operations/mentors/${mentor.id}`)); }
    catch { setError("Detail pembimbing belum bisa dimuat."); }
  }

  return <div className="flex flex-col gap-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
      <div><h1 className="text-3xl font-extrabold tracking-tight text-ink">Operasi PKL</h1><p className="mt-1 text-base text-ink-muted">Kelola data sekolah dan penempatan dari satu ruang kerja.</p></div>
      <div className="flex flex-wrap gap-2" role="tablist" aria-label="Jenis data operasi">
        {([["placements", "Placement"], ["students", "Siswa"], ["companies", "DUDI"], ["mentors", "Pembimbing"]] as const).map(([key, label]) => <button key={key} type="button" role="tab" aria-selected={view === key} onClick={() => { setView(key); setSelected([]); setSelectedCompany(null); setSelectedMentor(null); }} className={`min-h-11 border px-3 text-sm font-semibold ${view === key ? "border-primary bg-primary text-primary-ink" : "border-border text-ink"}`}>{label}</button>)}
      </div>
    </div>
    {message && <p role="status" className="border border-status-green/40 bg-status-green-bg p-3 text-sm text-ink">{message}</p>}
    {error && <p role="alert" className="border border-status-red/40 bg-status-red-bg p-3 text-sm text-status-red">{error}</p>}

    {view === "placements" && <section className="flex flex-col gap-4">
      <div className="flex flex-col gap-3 border-y border-border py-4 sm:flex-row sm:items-end sm:justify-between"><label className="flex-1 text-sm font-medium text-ink">Cari placement<input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nama siswa atau DUDI" className="mt-1 h-11 w-full border border-border bg-surface px-3 text-sm" /></label><button type="button" onClick={() => setShowWizard(true)} className="min-h-11 border border-primary bg-primary px-4 text-sm font-semibold text-primary-ink">Tambah placement</button></div>
      {selected.length > 0 && <div className="sticky bottom-20 z-10 flex flex-wrap items-center justify-between gap-3 border border-primary bg-surface p-3 text-sm shadow-lg lg:bottom-4"><span>{selected.length} placement dipilih</span><button type="button" onClick={() => setSelected([])} className="min-h-11 border border-border px-3 font-semibold text-ink">Batalkan pilihan</button></div>}
      <div className="hidden overflow-x-auto border-y border-border lg:block"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border bg-surface-muted text-xs uppercase tracking-wide text-ink-muted"><tr><th className="w-12 px-3 py-3"><input type="checkbox" aria-label="Pilih semua placement" checked={visiblePlacements.length > 0 && visiblePlacements.every((item) => selected.includes(item.id))} onChange={(event) => setSelected(event.target.checked ? visiblePlacements.map((item) => item.id) : [])} /></th><th className="px-3 py-3">Siswa</th><th className="px-3 py-3">DUDI</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Aksi</th></tr></thead><tbody className="divide-y divide-border">{visiblePlacements.map((placement) => <tr key={placement.id}><td className="px-3 py-4"><input type="checkbox" aria-label={`Pilih ${studentById.get(placement.studentId)?.fullName ?? "placement"}`} checked={selected.includes(placement.id)} onChange={(event) => setSelected((items) => event.target.checked ? [...items, placement.id] : items.filter((id) => id !== placement.id))} /></td><td className="px-3 py-4 font-medium text-ink">{studentById.get(placement.studentId)?.fullName ?? "Siswa tidak ditemukan"}</td><td className="px-3 py-4 text-ink-muted">{companyById.get(placement.companyId)?.name ?? "DUDI tidak ditemukan"}</td><td className="px-3 py-4"><StatusBadge status={placement.status === 0 ? "green" : "amber"} label={placement.status === 0 ? "Aktif" : placement.status === 1 ? "Selesai" : "Dihentikan"} /></td><td className="px-3 py-4"><Link href={`/app/bimbingan/${placement.id}`} className="font-semibold text-primary underline underline-offset-4">Buka</Link></td></tr>)}</tbody></table>{visiblePlacements.length === 0 && <EmptyState icon={<Icon name="list-checks" size={32} />} title="Belum ada placement" description="Tambahkan placement untuk menghubungkan siswa, DUDI, dan pembimbing." />}</div>
      <ul className="divide-y divide-border border-y border-border lg:hidden">{visiblePlacements.map((placement) => <li key={placement.id} className="flex flex-col gap-2 py-4"><div className="flex items-start justify-between gap-3"><div><span className="block font-medium text-ink">{studentById.get(placement.studentId)?.fullName ?? "Siswa"}</span><span className="block text-sm text-ink-muted">{companyById.get(placement.companyId)?.name ?? "DUDI belum tercatat"}</span></div><input type="checkbox" aria-label={`Pilih ${studentById.get(placement.studentId)?.fullName ?? "placement"}`} checked={selected.includes(placement.id)} onChange={(event) => setSelected((items) => event.target.checked ? [...items, placement.id] : items.filter((id) => id !== placement.id))} /></div><div className="flex items-center justify-between gap-3 text-sm"><StatusBadge status={placement.status === 0 ? "green" : "amber"} label={placement.status === 0 ? "Aktif" : placement.status === 1 ? "Selesai" : "Dihentikan"} /><Link href={`/app/bimbingan/${placement.id}`} className="min-h-11 pt-2 font-semibold text-primary underline underline-offset-4">Buka</Link></div></li>)}{visiblePlacements.length === 0 && <li><EmptyState icon={<Icon name="list-checks" size={32} />} title="Belum ada placement" description="Tambahkan placement untuk menghubungkan siswa, DUDI, dan pembimbing." /></li>}</ul>
    </section>}

    {view === "students" && <DataSection title="Siswa" actionLabel="Tambah siswa" onAction={() => setShowStudentForm((value) => !value)}><SearchBar value={query} onChange={setQuery} placeholder="Cari nama siswa" /><StudentForm open={showStudentForm} majors={majors} busy={busy} onCreated={(student) => { setStudents((items) => [student, ...items]); setShowStudentForm(false); setMessage("Siswa berhasil ditambahkan."); }} onRun={run} /><div className="hidden overflow-x-auto border-y border-border lg:block"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b border-border bg-surface-muted text-xs uppercase tracking-wide text-ink-muted"><tr><th className="px-3 py-3">Siswa</th><th className="px-3 py-3">Kelas</th><th className="px-3 py-3">NISN</th><th className="px-3 py-3">Aksi</th></tr></thead><tbody className="divide-y divide-border">{students.filter((student) => student.fullName.toLowerCase().includes(query.toLowerCase().trim())).map((student) => <tr key={student.id}><td className="px-3 py-4 font-medium text-ink">{student.fullName}</td><td className="px-3 py-4 text-ink-muted">{student.classroom}</td><td className="px-3 py-4 text-ink-muted">{student.nisn ?? "—"}</td><td className="px-3 py-4 text-primary">Detail</td></tr>)}</tbody></table></div><ul className="divide-y divide-border border-y border-border lg:hidden">{students.filter((student) => student.fullName.toLowerCase().includes(query.toLowerCase().trim())).map((student) => <li key={student.id} className="flex flex-col gap-1 py-4"><span className="font-medium text-ink">{student.fullName}</span><span className="text-sm text-ink-muted">{student.classroom} · {student.nisn ?? "NISN belum dicatat"}</span><span className="pt-2 text-sm text-primary">Detail</span></li>)}</ul></DataSection>}

    {view === "companies" && <DataSection title="DUDI" actionLabel="Tambah DUDI" onAction={() => setShowCompanyForm((value) => !value)}><SearchBar value={query} onChange={setQuery} placeholder="Cari nama, kota, atau sektor" /><CompanyForm open={showCompanyForm} busy={busy} onCreated={(company) => { setCompanies((items) => [company, ...items]); setShowCompanyForm(false); setMessage("DUDI berhasil ditambahkan."); }} onRun={run} /><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><div><div className="hidden overflow-x-auto border-y border-border lg:block"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-border bg-surface-muted text-xs uppercase tracking-wide text-ink-muted"><tr><th className="px-3 py-3">Nama DUDI</th><th className="px-3 py-3">Kota</th><th className="px-3 py-3">Sektor</th><th className="px-3 py-3">Aksi</th></tr></thead><tbody className="divide-y divide-border">{companies.filter((company) => `${company.name} ${company.city ?? ""} ${company.sector ?? ""}`.toLowerCase().includes(query.toLowerCase().trim())).map((company) => <tr key={company.id}><td className="px-3 py-4 font-medium text-ink">{company.name}</td><td className="px-3 py-4 text-ink-muted">{company.city ?? "—"}</td><td className="px-3 py-4 text-ink-muted">{company.sector ?? "—"}</td><td className="px-3 py-4"><button type="button" onClick={() => setSelectedCompany(company)} className="font-semibold text-primary underline underline-offset-4">Detail</button></td></tr>)}</tbody></table></div><ul className="divide-y divide-border border-y border-border lg:hidden">{companies.filter((company) => `${company.name} ${company.city ?? ""} ${company.sector ?? ""}`.toLowerCase().includes(query.toLowerCase().trim())).map((company) => <li key={company.id} className="flex items-center justify-between gap-3 py-4"><div><span className="block font-medium text-ink">{company.name}</span><span className="text-sm text-ink-muted">{company.city ?? "Kota belum dicatat"} · {company.sector ?? "Sektor belum dicatat"}</span></div><button type="button" onClick={() => setSelectedCompany(company)} className="min-h-11 shrink-0 font-semibold text-primary underline underline-offset-4">Detail</button></li>)}</ul></div>{selectedCompany && <CompanyDetail company={selectedCompany} placements={placements} studentById={studentById} onClose={() => setSelectedCompany(null)} />}</div></DataSection>}

    {view === "mentors" && <DataSection title="Pembimbing industri" actionLabel="" onAction={() => undefined}><SearchBar value={query} onChange={setQuery} placeholder="Cari nama pembimbing" /><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><div><div className="hidden overflow-x-auto border-y border-border lg:block"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-border bg-surface-muted text-xs uppercase tracking-wide text-ink-muted"><tr><th className="px-3 py-3">Pembimbing</th><th className="px-3 py-3">Siswa</th><th className="px-3 py-3">Jurnal menunggu</th><th className="px-3 py-3">Penilaian</th><th className="px-3 py-3" /></tr></thead><tbody className="divide-y divide-border">{mentors.filter((mentor) => mentor.fullName.toLowerCase().includes(query.toLowerCase().trim())).map((mentor) => <tr key={mentor.id}><td className="px-3 py-4"><span className="block font-medium text-ink">{mentor.fullName}</span><span className="text-xs text-ink-muted">{mentor.email}</span></td><td className="px-3 py-4 text-ink-muted">{mentor.assignedStudentCount}</td><td className="px-3 py-4 text-ink-muted">{mentor.pendingJournalCount}</td><td className="px-3 py-4 text-ink-muted">{mentor.incompleteAssessmentCount} belum final</td><td className="px-3 py-4"><button type="button" onClick={() => void openMentor(mentor)} className="font-semibold text-primary underline underline-offset-4">Detail</button></td></tr>)}</tbody></table>{mentors.length === 0 && <EmptyState icon={<Icon name="graduation-cap" size={32} />} title="Belum ada pembimbing terhubung" description="Data pembimbing industri akan muncul setelah mentor menerima undangan." />}</div><ul className="divide-y divide-border border-y border-border lg:hidden">{mentors.filter((mentor) => mentor.fullName.toLowerCase().includes(query.toLowerCase().trim())).map((mentor) => <li key={mentor.id} className="flex flex-col gap-2 py-4"><div className="flex items-start justify-between gap-3"><div><span className="block font-medium text-ink">{mentor.fullName}</span><span className="block max-w-[16rem] truncate text-xs text-ink-muted">{mentor.email}</span></div><button type="button" onClick={() => void openMentor(mentor)} className="min-h-11 shrink-0 font-semibold text-primary underline underline-offset-4">Detail</button></div><span className="text-sm text-ink-muted">{mentor.assignedStudentCount} siswa · {mentor.pendingJournalCount} jurnal menunggu</span><span className="text-xs text-ink-muted">Penilaian: {mentor.incompleteAssessmentCount} belum final</span></li>)}</ul>{mentors.length === 0 && <div className="lg:hidden"><EmptyState icon={<Icon name="graduation-cap" size={32} />} title="Belum ada pembimbing terhubung" description="Data pembimbing industri akan muncul setelah mentor menerima undangan." /></div>}</div>{selectedMentor && <MentorDetail detail={selectedMentor} onClose={() => setSelectedMentor(null)} />}</div></DataSection>}

    {showWizard && <PlacementWizard periods={periods} periodId={periodId} students={students} companies={companies} staff={staff} busy={busy} onCancel={() => setShowWizard(false)} onRun={run} onCreated={(placement) => { setPlacements((items) => [placement, ...items]); setShowWizard(false); setMessage("Placement berhasil dibuat."); }} />}
  </div>;
}

function DataSection({ title, actionLabel, onAction, children }: { title: string; actionLabel: string; onAction: () => void; children: React.ReactNode }) { return <section className="flex flex-col gap-4"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold text-ink">{title}</h2>{actionLabel && <button type="button" onClick={onAction} className="min-h-11 border border-primary px-4 text-sm font-semibold text-primary">{actionLabel}</button>}</div>{children}</section>; }
function SearchBar({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="block text-sm font-medium text-ink">Cari<input type="search" value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-1 h-11 w-full border border-border bg-surface px-3 text-sm" /></label>; }
function StudentForm({ open, majors, busy, onCreated, onRun }: { open: boolean; majors: MajorOptionDto[]; busy: boolean; onCreated: (student: StudentDto) => void; onRun: (action: () => Promise<void>) => Promise<void> }) { const [fullName, setFullName] = useState(""); const [nisn, setNisn] = useState(""); const [classroom, setClassroom] = useState(""); const [majorId, setMajorId] = useState(majors[0]?.id ?? ""); if (!open) return null; return <form className="grid gap-3 border-y border-border bg-surface-muted p-4 md:grid-cols-4" onSubmit={(event) => { event.preventDefault(); if (!majorId) return; void onRun(async () => { const student = await apiClient.post<StudentDto>("/students", { fullName, nisn: nisn || null, classroom, majorId }); onCreated(student); setFullName(""); setNisn(""); setClassroom(""); }); }}><div className="md:col-span-4" role="status">{majors.length === 0 ? <p className="text-sm text-status-red">Belum ada master jurusan. Tambahkan jurusan sebelum membuat siswa.</p> : <p className="text-sm text-ink-muted">Pilih jurusan dari master tenant agar data siswa konsisten.</p>}</div><label className="text-sm text-ink">Nama<input required value={fullName} onChange={(event) => setFullName(event.target.value)} className="mt-1 h-11 w-full border border-border px-3" /></label><label className="text-sm text-ink">NISN<input value={nisn} onChange={(event) => setNisn(event.target.value)} className="mt-1 h-11 w-full border border-border px-3" /></label><label className="text-sm text-ink">Kelas<input required value={classroom} onChange={(event) => setClassroom(event.target.value)} className="mt-1 h-11 w-full border border-border px-3" /></label><label className="text-sm text-ink">Jurusan<select required disabled={majors.length === 0} value={majorId} onChange={(event) => setMajorId(event.target.value)} className="mt-1 h-11 w-full border border-border px-3"><option value="">Pilih jurusan</option>{majors.map((major) => <option key={major.id} value={major.id}>{major.name}</option>)}</select></label><button type="submit" disabled={busy || majors.length === 0} className="min-h-11 border border-primary px-4 text-sm font-semibold text-primary md:col-span-4 md:justify-self-start">Simpan siswa</button></form>; }
function CompanyForm({ open, busy, onCreated, onRun }: { open: boolean; busy: boolean; onCreated: (company: CompanyDto) => void; onRun: (action: () => Promise<void>) => Promise<void> }) { const [name, setName] = useState(""); const [city, setCity] = useState(""); const [sector, setSector] = useState(""); const [address, setAddress] = useState(""); const [contactPerson, setContactPerson] = useState(""); if (!open) return null; return <form className="grid gap-3 border-y border-border bg-surface-muted p-4 md:grid-cols-3" onSubmit={(event) => { event.preventDefault(); void onRun(async () => { const company = await apiClient.post<CompanyDto>("/companies/propose", { name, city: city || null, sector: sector || null, address: address || null, contactPerson: contactPerson || null }); onCreated(company); setName(""); setCity(""); setSector(""); setAddress(""); setContactPerson(""); }); }}><label className="text-sm text-ink">Nama DUDI<input required value={name} onChange={(event) => setName(event.target.value)} className="mt-1 h-11 w-full border border-border px-3" /></label><label className="text-sm text-ink">Kota<input value={city} onChange={(event) => setCity(event.target.value)} className="mt-1 h-11 w-full border border-border px-3" /></label><label className="text-sm text-ink">Sektor<input value={sector} onChange={(event) => setSector(event.target.value)} className="mt-1 h-11 w-full border border-border px-3" /></label><label className="text-sm text-ink md:col-span-2">Alamat<input value={address} onChange={(event) => setAddress(event.target.value)} className="mt-1 h-11 w-full border border-border px-3" /></label><label className="text-sm text-ink">Kontak PIC<input value={contactPerson} onChange={(event) => setContactPerson(event.target.value)} className="mt-1 h-11 w-full border border-border px-3" /></label><button type="submit" disabled={busy} className="min-h-11 border border-primary px-4 text-sm font-semibold text-primary md:col-span-3 md:justify-self-start">Simpan DUDI</button></form>; }
function CompanyDetail({ company, placements, studentById, onClose }: { company: CompanyDto; placements: PlacementDto[]; studentById: Map<string, StudentDto>; onClose: () => void }) { const assigned = placements.filter((placement) => placement.companyId === company.id); return <aside className="border border-border bg-surface p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-ink">{company.name}</h3><p className="text-sm text-ink-muted">{company.city ?? "Kota belum dicatat"} · {company.sector ?? "Sektor belum dicatat"}</p><p className="mt-2 text-sm text-ink">{company.address ?? "Alamat belum dicatat"}</p><p className="text-sm text-ink-muted">PIC: {company.contactPerson ?? "Belum dicatat"}</p></div><button type="button" onClick={onClose} className="min-h-11 px-2 text-sm font-semibold text-primary">Tutup</button></div><div className="mt-5 border-t border-border pt-4"><p className="text-xs font-semibold uppercase tracking-wide text-ink-muted">Operasional</p><p className="mt-1 text-sm text-ink">{assigned.length} placement pada periode terpilih</p><ul className="mt-3 divide-y divide-border">{assigned.map((placement) => <li key={placement.id} className="py-3 text-sm"><span className="block font-medium text-ink">{studentById.get(placement.studentId)?.fullName ?? "Siswa"}</span><span className="text-ink-muted">Slot belum ditetapkan untuk placement ini.</span></li>)}</ul></div></aside>; }
function MentorDetail({ detail, onClose }: { detail: TenantMentorDetailDto; onClose: () => void }) { return <aside className="border border-border bg-surface p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-ink">{detail.fullName}</h3><p className="text-sm text-ink-muted">{detail.email}</p></div><button type="button" onClick={onClose} className="min-h-11 px-2 text-sm font-semibold text-primary">Tutup</button></div><dl className="mt-5 grid gap-3 border-y border-border py-4 text-sm"><div><dt className="text-ink-muted">Status akun</dt><dd className="font-medium text-ink">{detail.isActive ? "Aktif" : "Tidak aktif"}</dd></div><div><dt className="text-ink-muted">Aktivitas jurnal terakhir</dt><dd className="font-medium text-ink">{detail.lastJournalAt ? new Date(detail.lastJournalAt).toLocaleDateString("id-ID") : "Belum ada"}</dd></div></dl><h4 className="mt-4 text-sm font-semibold text-ink">Siswa ditugaskan</h4><ul className="mt-2 divide-y divide-border">{detail.students.map((student) => <li key={student.placementId} className="py-3 text-sm"><span className="block font-medium text-ink">{student.studentName}</span><span className="block text-ink-muted">{student.companyName}</span><span className="mt-1 block text-xs text-ink-muted">{student.pendingJournalCount} jurnal menunggu · Penilaian {student.assessmentStatus}</span></li>)}</ul></aside>; }
